export const htmlAttributes = new Map<string, boolean>();
htmlAttributes.set('accept', false);
htmlAttributes.set('bind', false);
htmlAttributes.set("accept-charset", false);
htmlAttributes.set('accesskey', false);
htmlAttributes.set('action', false);
htmlAttributes.set('align', false);
htmlAttributes.set('allow', false);
htmlAttributes.set('alt', false);
htmlAttributes.set('async', false);
htmlAttributes.set('autocapitalize', false);
htmlAttributes.set('autofocus', false);
htmlAttributes.set('autoplay', false);
htmlAttributes.set('background', false);
htmlAttributes.set('bgcolor', false);
htmlAttributes.set('border', false);
htmlAttributes.set('buffered', false);
htmlAttributes.set('capture', false);
htmlAttributes.set('challenge', false);
htmlAttributes.set('charset', false);
htmlAttributes.set('checked', false);
htmlAttributes.set('cite', false);
htmlAttributes.set('class', false);
htmlAttributes.set('code', false);
htmlAttributes.set('codebase', false);
htmlAttributes.set('color', false);
htmlAttributes.set('cols', false);
htmlAttributes.set('colspan', false);
htmlAttributes.set('content', false);
htmlAttributes.set('contenteditable', false);
htmlAttributes.set('contextmenu', false);
htmlAttributes.set('controls', false);
htmlAttributes.set('coords', false);
htmlAttributes.set('crossorigin', false);
htmlAttributes.set('csp', false);
htmlAttributes.set('data', false);
htmlAttributes.set('data-*', false);
htmlAttributes.set('datetime', false);
htmlAttributes.set('decoding', false);
htmlAttributes.set('default', false);
htmlAttributes.set('defer', false);
htmlAttributes.set('dir', false);
htmlAttributes.set('dirname', false);
htmlAttributes.set('disabled', false);
htmlAttributes.set('download', false);
htmlAttributes.set('draggable', false);
htmlAttributes.set('enctype', false);
htmlAttributes.set('enterkeyhint', false);
htmlAttributes.set('for', false);
htmlAttributes.set('form', false);
htmlAttributes.set('formaction', false);
htmlAttributes.set('formenctype', false);
htmlAttributes.set('formmethod', false);
htmlAttributes.set('formnovalidate', false);
htmlAttributes.set('formtarget', false);
htmlAttributes.set('headers', false);
htmlAttributes.set('height', false);
htmlAttributes.set('hidden', false);
htmlAttributes.set('high', false);
htmlAttributes.set('href', false);
htmlAttributes.set('hreflang', false);
htmlAttributes.set('http-equiv', false);
htmlAttributes.set('icon', false);
htmlAttributes.set('id', false);
htmlAttributes.set('importance', false);
htmlAttributes.set('integrity', false);
htmlAttributes.set('intrinsicsize', false);
htmlAttributes.set('inputmode', false);
htmlAttributes.set('ismap', false);
htmlAttributes.set('itemprop', false);
htmlAttributes.set('keytype', false);
htmlAttributes.set('kind', false);
htmlAttributes.set('label', false);
htmlAttributes.set('lang', false);
htmlAttributes.set('language', false);
htmlAttributes.set('loading', false);
htmlAttributes.set('list', false);
htmlAttributes.set('loop', false);
htmlAttributes.set('low', false);
htmlAttributes.set('manifest', false);
htmlAttributes.set('max', false);
htmlAttributes.set('maxlength', false);
htmlAttributes.set('minlength', false);
htmlAttributes.set('media', false);
htmlAttributes.set('method', false);
htmlAttributes.set('min', false);
htmlAttributes.set('multiple', false);
htmlAttributes.set('muted', false);
htmlAttributes.set('name', false);
htmlAttributes.set('novalidate', false);
htmlAttributes.set('open', false);
htmlAttributes.set('optimum', false);
htmlAttributes.set('pattern', false);
htmlAttributes.set('ping', false);
htmlAttributes.set('placeholder', false);
htmlAttributes.set('poster', false);
htmlAttributes.set('preload', false);
htmlAttributes.set('radiogroup', false);
htmlAttributes.set('readonly', false);
htmlAttributes.set('referrerpolicy', false);
htmlAttributes.set('rel', false);
htmlAttributes.set('required', false);
htmlAttributes.set('reversed', false);
htmlAttributes.set('role', false);
htmlAttributes.set('rows', false);
htmlAttributes.set('rowspan', false);
htmlAttributes.set('sandbox', false);
htmlAttributes.set('scope', false);
htmlAttributes.set('scoped', false);
htmlAttributes.set('selected', false);
htmlAttributes.set('shape', false);
htmlAttributes.set('size', false);
htmlAttributes.set('sizes', false);
htmlAttributes.set('slot', false);
htmlAttributes.set('span', false);
htmlAttributes.set('spellcheck', false);
htmlAttributes.set('src', false);
htmlAttributes.set('srcdoc', false);
htmlAttributes.set('srclang', false);
htmlAttributes.set('srcset', false);
htmlAttributes.set('start', false);
htmlAttributes.set('step', false);
htmlAttributes.set('style', false);
htmlAttributes.set('summary', false);
htmlAttributes.set('tabindex', false);
htmlAttributes.set('target', false);
htmlAttributes.set('title', false);
htmlAttributes.set('translate', false);
htmlAttributes.set('type', false);
htmlAttributes.set('usemap', false);
htmlAttributes.set('value', false);
htmlAttributes.set('width', false);
htmlAttributes.set('wrap', false);
htmlAttributes.set('aria-readonly', true)
htmlAttributes.set('className', false)
 

 
htmlAttributes.set('xml:base',false)
htmlAttributes.set('xml:lang',false)
htmlAttributes.set('xml:space', false)
htmlAttributes.set('xmlns:xlink', false)
htmlAttributes.set('xmlns', false)

htmlAttributes.set('alignment-baseline',false);
htmlAttributes.set('baseline-shift',false);
htmlAttributes.set('clip',false);
htmlAttributes.set('clip-path',false);
htmlAttributes.set('clip-rule',false);
htmlAttributes.set('color',false);
htmlAttributes.set('color-interpolation',false);
htmlAttributes.set('color-interpolation-filters',false);
htmlAttributes.set('color-profile',false);
htmlAttributes.set('color-rendering',false);
htmlAttributes.set('cursor',false);
htmlAttributes.set('direction',false);
htmlAttributes.set('display',false);
htmlAttributes.set('dominant-baseline',false);
htmlAttributes.set('enable-background',false);
htmlAttributes.set('fill',false);
htmlAttributes.set('fill-opacity',false);
htmlAttributes.set('fill-rule',false);
htmlAttributes.set('filter',false);
htmlAttributes.set('flood-color',false);
htmlAttributes.set('flood-opacity',false);
htmlAttributes.set('font-family',false);
htmlAttributes.set('font-size',false);
htmlAttributes.set('font-size-adjust',false);
htmlAttributes.set('font-stretch',false);
htmlAttributes.set('font-style',false);
htmlAttributes.set('font-variant',false);
htmlAttributes.set('font-weight',false); 
htmlAttributes.set('glyph-orientation-horizontal',false);
htmlAttributes.set('glyph-orientation-vertical',false);
htmlAttributes.set('image-rendering',false);
htmlAttributes.set('kerning',false);
htmlAttributes.set('letter-spacing',false);
htmlAttributes.set('lighting-color',false);
htmlAttributes.set('marker-end',false);
htmlAttributes.set('marker-mid',false);
htmlAttributes.set('marker-start',false);
htmlAttributes.set('mask',false);
htmlAttributes.set('opacity',false);
htmlAttributes.set('overflow',false);
htmlAttributes.set('pointer-events',false);
htmlAttributes.set('shape-rendering',false);
htmlAttributes.set('stop-color',false);
htmlAttributes.set('stop-opacity',false);
htmlAttributes.set('stroke',false);
htmlAttributes.set('stroke-dasharray',false);
htmlAttributes.set('stroke-dashoffset',false);
htmlAttributes.set('stroke-linecap',false);
htmlAttributes.set('stroke-linejoin',false);
htmlAttributes.set('stroke-miterlimit',false);
htmlAttributes.set('stroke-opacity',false);
htmlAttributes.set('stroke-width',false);
htmlAttributes.set('text-anchor',false);
htmlAttributes.set('text-decoration',false);
htmlAttributes.set('text-rendering',false);
htmlAttributes.set('transform',false);
htmlAttributes.set('transform-origin',false);
htmlAttributes.set('unicode-bidi',false);
htmlAttributes.set('vector-effect',false);
htmlAttributes.set('visibility',false);
htmlAttributes.set('word-spacing',false);
htmlAttributes.set('writing-mode', false);

htmlAttributes.set('x1', false);
htmlAttributes.set('x2', false);
htmlAttributes.set('y1', false);
htmlAttributes.set('y2', false);
htmlAttributes.set('offset', false);
htmlAttributes.set('d', false);
htmlAttributes.set('preserveaspectratio', false);
htmlAttributes.set('viewbox', false);
htmlAttributes.set('viewBox', false);


export const htmlEvents = new Map<string, boolean>();

htmlEvents.set("onafterprint",false);
htmlEvents.set("onbeforeprint",false);
htmlEvents.set("onbeforeunload",false);
htmlEvents.set("onerror",false);
htmlEvents.set("onhashchange",false);
htmlEvents.set("onload",false);
htmlEvents.set("onmessage",false);
htmlEvents.set("onoffline",false);
htmlEvents.set("ononline",false);
htmlEvents.set("onpagehide",false);
htmlEvents.set("onpageshow",false);
htmlEvents.set("onpopstate",false);
htmlEvents.set("onresize",false);
htmlEvents.set("onstorage",false);
htmlEvents.set("onunload",false);
htmlEvents.set("onblur",false);
htmlEvents.set("onchange",false);
htmlEvents.set("oncontextmenu",false);
htmlEvents.set("onfocus",false);
htmlEvents.set("oninput",false);
htmlEvents.set("oninvalid",false);
htmlEvents.set("onreset",false);
htmlEvents.set("onsearch",false);
htmlEvents.set("onselect",false);
htmlEvents.set("onsubmit",false);
htmlEvents.set("onkeydown ",false);
htmlEvents.set("onkeypress ",false);
htmlEvents.set("onkeyup",false);
htmlEvents.set("onclick",false);
htmlEvents.set("ondblclick",false);
htmlEvents.set("onmousedown",false);
htmlEvents.set("onmousemove",false);
htmlEvents.set("onmouseout",false);
htmlEvents.set("onmouseover",false);
htmlEvents.set("onmouseup",false);
htmlEvents.set("onmousewheel",false);
htmlEvents.set("onwheel",false);
htmlEvents.set("ondrag",false);
htmlEvents.set("ondragend",false);
htmlEvents.set("ondragenter",false);
htmlEvents.set("ondragleave",false);
htmlEvents.set("ondragover",false);
htmlEvents.set("ondragstart",false);
htmlEvents.set("ondrop",false);
htmlEvents.set("onscroll",false);
htmlEvents.set("oncopy",false);
htmlEvents.set("oncut",false);
htmlEvents.set("onpaste",false);
htmlEvents.set("onabort",false);
htmlEvents.set("oncanplay",false);
htmlEvents.set("oncanplaythrough",false);
htmlEvents.set("oncuechange",false);
htmlEvents.set("ondurationchange",false);
htmlEvents.set("onemptied",false);
htmlEvents.set("onended",false);
htmlEvents.set("onerror",false);
htmlEvents.set("onloadeddata",false);
htmlEvents.set("onloadedmetadata",false);
htmlEvents.set("onloadstart",false);
htmlEvents.set("onpause",false);
htmlEvents.set("onplay",false);
htmlEvents.set("onplaying",false);
htmlEvents.set("onprogress",false);
htmlEvents.set("onratechange",false);
htmlEvents.set("onseeked",false);
htmlEvents.set("onseeking",false);
htmlEvents.set("onstalled",false);
htmlEvents.set("onsuspend",false);
htmlEvents.set("ontimeupdate",false);
htmlEvents.set("onvolumechange",false);
htmlEvents.set("onwaiting",false);
htmlEvents.set("ontoggle",false);